# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/129/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/129/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/lyp/1_Code/nct/Blackmagic DeckLink SDK 11.6/Linux/tests"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/lyp/1_Code/nct/Blackmagic DeckLink SDK 11.6/Linux/tests"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/129/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/129/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/lyp/1_Code/nct/Blackmagic DeckLink SDK 11.6/Linux/tests/CMakeFiles" "/home/lyp/1_Code/nct/Blackmagic DeckLink SDK 11.6/Linux/tests/CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/lyp/1_Code/nct/Blackmagic DeckLink SDK 11.6/Linux/tests/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DisplayVideo3D

# Build rule for target.
DisplayVideo3D: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DisplayVideo3D
.PHONY : DisplayVideo3D

# fast build rule for target.
DisplayVideo3D/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayVideo3D.dir/build.make CMakeFiles/DisplayVideo3D.dir/build
.PHONY : DisplayVideo3D/fast

DLOutputCallback.o: DLOutputCallback.cpp.o

.PHONY : DLOutputCallback.o

# target to build an object file
DLOutputCallback.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayVideo3D.dir/build.make CMakeFiles/DisplayVideo3D.dir/DLOutputCallback.cpp.o
.PHONY : DLOutputCallback.cpp.o

DLOutputCallback.i: DLOutputCallback.cpp.i

.PHONY : DLOutputCallback.i

# target to preprocess a source file
DLOutputCallback.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayVideo3D.dir/build.make CMakeFiles/DisplayVideo3D.dir/DLOutputCallback.cpp.i
.PHONY : DLOutputCallback.cpp.i

DLOutputCallback.s: DLOutputCallback.cpp.s

.PHONY : DLOutputCallback.s

# target to generate assembly for a file
DLOutputCallback.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayVideo3D.dir/build.make CMakeFiles/DisplayVideo3D.dir/DLOutputCallback.cpp.s
.PHONY : DLOutputCallback.cpp.s

DisplayVideo3D.o: DisplayVideo3D.cpp.o

.PHONY : DisplayVideo3D.o

# target to build an object file
DisplayVideo3D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayVideo3D.dir/build.make CMakeFiles/DisplayVideo3D.dir/DisplayVideo3D.cpp.o
.PHONY : DisplayVideo3D.cpp.o

DisplayVideo3D.i: DisplayVideo3D.cpp.i

.PHONY : DisplayVideo3D.i

# target to preprocess a source file
DisplayVideo3D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayVideo3D.dir/build.make CMakeFiles/DisplayVideo3D.dir/DisplayVideo3D.cpp.i
.PHONY : DisplayVideo3D.cpp.i

DisplayVideo3D.s: DisplayVideo3D.cpp.s

.PHONY : DisplayVideo3D.s

# target to generate assembly for a file
DisplayVideo3D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayVideo3D.dir/build.make CMakeFiles/DisplayVideo3D.dir/DisplayVideo3D.cpp.s
.PHONY : DisplayVideo3D.cpp.s

home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.o: home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.cpp.o

.PHONY : home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.o

# target to build an object file
home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayVideo3D.dir/build.make CMakeFiles/DisplayVideo3D.dir/home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.cpp.o
.PHONY : home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.cpp.o

home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.i: home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.cpp.i

.PHONY : home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.i

# target to preprocess a source file
home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayVideo3D.dir/build.make CMakeFiles/DisplayVideo3D.dir/home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.cpp.i
.PHONY : home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.cpp.i

home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.s: home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.cpp.s

.PHONY : home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.s

# target to generate assembly for a file
home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayVideo3D.dir/build.make CMakeFiles/DisplayVideo3D.dir/home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.cpp.s
.PHONY : home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayVideo3D.dir/build.make CMakeFiles/DisplayVideo3D.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayVideo3D.dir/build.make CMakeFiles/DisplayVideo3D.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayVideo3D.dir/build.make CMakeFiles/DisplayVideo3D.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DisplayVideo3D"
	@echo "... DLOutputCallback.o"
	@echo "... DLOutputCallback.i"
	@echo "... DLOutputCallback.s"
	@echo "... DisplayVideo3D.o"
	@echo "... DisplayVideo3D.i"
	@echo "... DisplayVideo3D.s"
	@echo "... home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.o"
	@echo "... home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.i"
	@echo "... home/lyp/1_Code/nct/Blackmagic_DeckLink_SDK_11.6/Linux/include/DeckLinkAPIDispatch.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

